### PR TITLE
Q3

### PR DESCRIPTION
**Pull request by MwMaki**
Question three Javascript and ruby

### CODE REVIEW

File: Q3.txt [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+
+Ruby
+
+b = [5, 10, 23, 10, 7, 9, 39, 16, 1, 12, 36, 20, 50]
+
+
+puts "---If the number odd then multiplie it  by 2 ----"
+b.each do |element|
+	if (element%2 != 0)
+		puts (element*2)
```
Comment (malkhafaji) [inline Q3.txt]: This is right, but I want you to start learning some advanced syntax. In ruby, you can immediately select all the elements that satisfy a criteria using the following syntax:
b.select {|c| c%2 == 0}
This means that you are only selecting elements from b that satisfy the condition defined inside the { and }. c is nothing but a temporary holder for every element in a. So, you can do something like this to print even numbers * 2:
b.select{|c| c%2 == 0}.each{|d| puts d*2}

File: Q3.txt [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+
+
+console.log("---If the number odd then multiplie it  by 2 ----");
+for(i=0;i<b.length;i++){
+	if(b[i]%2 !==0){
+		console.log(b[i]*2);
+	}
+}
+
+console.log("---If the number even subtract one---");
```
Comment (MwMaki) [inline Q3.txt]: to take all the array and apply first condition then print the result ,after that will take the array the and apply the 2nd condition ..etc 
if I do one loop it will take the first element and apply it to each condition and print for each condition ,then the 2nd ....etc

File: Q3.txt [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+for(i=0;i<b.length;i++){
+	if(b[i]%5 === 0){
+	console.log(Math.pow(b[i],2));
+	}
+}
+
+console.log("--IF the number divisible by 10 do loop from 0 to number(step 10)--");
+for(i=0;i<b.length;i++){
+	if(b[i]%10 === 0){
+		for(j=0;j<=b[i];j+=10)
```
Comment (MwMaki) [inline Q3.txt]: what do you mean?? I used the {} in the inner loop  too

File: Q3.txt (hunk 1 above)
Comment (MwMaki) [inline Q3.txt]: OK, but why 	b.select(|c| c%2 == 0).each(|d| puts d*2)

not working ?

Comment (malkhafaji) [inline Q3.txt]: each is a block of code, so its body must have { and } NOT ( and ). It is not a function

File: Q3.txt (hunk 3 above)
Comment (malkhafaji) [inline Q3.txt]: Line 30

File: Q3.txt (hunk 2 above)
Comment (malkhafaji) [inline Q3.txt]: Then you can store the elements in arrays, and then print those at the end. Looping over the same array multiple times is bad practice

Comment (MwMaki) [inline Q3.txt]: I stored the results in arrays but when i'm printing the arrays there are empty elements in the array 
just like [ 10, , 46, , 14, 18, 78, , 2 ]

File: Q3.txt (hunk 3 above)
Comment (MwMaki) [inline Q3.txt]: Ok I saw it missing {},
